(function(gpio) {
  gpio.getPins = function(microController) {
    var arduinoUno = [{
      pin: 0,
      description: 'PD0(RXD)',
      isGpio: true
    }, {
      pin: 1,
      description: 'PD1(TXD)',
      isGpio: true
    }, {
      pin: 2,
      description: 'PD2(INTO)',
      isGpio: true
    }, {
      pin: 3,
      description: 'PD3(INT1)',
      isGpio: true
    }, {
      pin: 4,
      description: 'PD4',
      isGpio: true
    }, {
      pin: 5,
      description: 'PD5',
      isGpio: true
    }, {
      pin: 6,
      description: 'PD6',
      isGpio: true
    }, {
      pin: 7,
      description: 'PD7',
      isGpio: true
    }, {
      pin: 8,
      description: 'PB0',
      isGpio: true
    }, {
      pin: 9,
      description: 'PB1',
      isGpio: true
    }, {
      pin: 10,
      description: 'PB2(SS)',
      isGpio: true
    }, {
      pin: 11,
      description: 'PB3(MOSI)',
      isGpio: true
    }, {
      pin: 12,
      description: 'PB4(MISO)',
      isGpio: true
    }, {
      pin: 13,
      description: 'PB5(SCK)',
      isGpio: true
    }, {
      pin: 'A0',
      description: 'PC0',
      isGpio: true
    }, {
      pin: 'A1',
      description: 'PC1',
      isGpio: true
    }, {
      pin: 'A2',
      description: 'PC2',
      isGpio: true
    }, {
      pin: 'A3',
      description: 'PC3',
      isGpio: true
    }, {
      pin: 'A4',
      description: 'PC4(SDA)',
      isGpio: true
    }, {
      pin: 'A5',
      description: 'PC5(SCL)',
      isGpio: true
    }];

    var gpioPinsRev2 = [{
      pin: 1,
      description: '3.3V',
      isGpio: false
    }, {
      pin: 2,
      description: '5V',
      isGpio: false
    }, {
      pin: 3,
      description: 'GPIO2',
      isGpio: true
    }, {
      pin: 4,
      description: '5V',
      isGpio: false
    }, {
      pin: 5,
      description: 'GPIO3',
      isGpio: true
    }, {
      pin: 6,
      description: 'GND',
      isGpio: false
    }, {
      pin: 7,
      description: 'GPIO4',
      isGpio: true
    }, {
      pin: 8,
      description: 'GPIO14',
      isGpio: true
    }, {
      pin: 9,
      description: 'GND',
      isGpio: false
    }, {
      pin: 10,
      description: 'GPIO15',
      isGpio: true
    }, {
      pin: 11,
      description: 'GPIO17',
      isGpio: true
    }, {
      pin: 12,
      description: 'GPIO18',
      isGpio: true
    }, {
      pin: 13,
      description: 'GPIO27',
      isGpio: true
    }, {
      pin: 14,
      description: 'GND',
      isGpio: false
    }, {
      pin: 15,
      description: 'GPIO22',
      isGpio: true
    }, {
      pin: 16,
      description: 'GPIO23',
      isGpio: true
    }, {
      pin: 17,
      description: '3.3V',
      isGpio: false
    }, {
      pin: 18,
      description: 'GPIO24',
      isGpio: true
    }, {
      pin: 19,
      description: 'GPIO10',
      isGpio: true
    }, {
      pin: 20,
      description: 'GND',
      isGpio: false
    }, {
      pin: 21,
      description: 'GPIO9',
      isGpio: true
    }, {
      pin: 22,
      description: 'GPIO25',
      isGpio: true
    }, {
      pin: 23,
      description: 'GPIO23',
      isGpio: true
    }, {
      pin: 24,
      description: 'GPIO8',
      isGpio: true,
      reserved: 'camera'
    }, {
      pin: 25,
      description: 'GND',
      isGpio: false
    }, {
      pin: 26,
      description: 'GPIO7',
      isGpio: true,
      reserved: 'camera'
    }];

    var allControllers = [{
      microController: 'pi_rev_2_model_b',
      pins: gpioPinsRev2
    }, {
      microController: 'arduino',
      pins: arduinoUno
    }];

    for (var i = 0; i < allControllers.length; i++) {
      if (allControllers[i].microController == microController) {
        return allControllers[i];
      }
    }
  };
})(module.exports);
